### ISSUE TITLE
Update Outdated Benchmarks

### ISSUE THREAD

**Issue by Alexhuszagh** [Alexhuszagh/fast-float-rust#16]
The float parsers used have had numerous improvements, often implementing the same algorithms as `fast-float`, and changes to the Rust compiler can make certain optimizations that previous versions could not.

**Comment by Alexhuszagh** [comment]
I do not have access to an Apple M1 nor an AMD Rome CPU, so I can only update one of the listed benchmarks. Anyone with access to that hardware would be greatly appreciated. I believe the M1 could be done via our CI pipelines.

**Comment by jqnatividad** [comment]
Yep! GH has Apple Silicon action runners and it'd be great if the benchmarks can be refreshed on release.

Just the same, I have access to Apple M1, M2 and M3 machines @Alexhuszagh . Let me know if I can help in the meantime by running the Apple Silicon benchmarks manually.
